/* офлайн-кэш: сначала сеть, при отсутствии интернета — кэш */
const CACHE = 'murlok-v23';
const FILES = ['./', 'index.html', 'style.css?v=23', 'content/extra/cases-extra.js?v=23', 'engine.js?v=23', 'lines.js?v=23', 'cat.js?v=23', 'sounds.js?v=23', 'app.js?v=23', 'house.js?v=23', 'chat.js?v=23', 'studio.js?v=23', 'chibi.js?v=23', 'games.js?v=23', 'academy.js?v=23', 'content/space.js?v=23', 'content/safety.js?v=23', 'content/teen.js?v=23', 'content/think.js?v=23', 'content/extra/read-texts.js?v=23', 'content/extra/games-extra.js?v=23', 'content/read.js?v=23', 'content/talk.js?v=23', 'content/world.js?v=23', 'content/body.js?v=23', 'content/health.js?v=23', 'content/creative.js?v=23', 'content/math4.js?v=23', 'content/stories.js?v=23', 'content/obzh.js?v=23', 'content/extra/stars.js?v=23', 'content/extra/q-space-world-body.js?v=23', 'content/extra/q-safety-talk-health.js?v=23', 'content/extra/q-think-teen-read.js?v=23', 'acad-games.js?v=23', 'creative-games.js?v=23', 'school4.js?v=23', 'taskbank.js?v=23', 'starmap.js?v=23', 'spacetrip.js?v=23', 'drills.js?v=23', 'column.js?v=23', 'salon.js?v=23', 'fitting.js?v=23', 'photo.js?v=23', 'friends.js?v=23', 'extras.js?v=23', 'wardrobe.js?v=23', 'diplomas.js?v=23', 'awards.js?v=23', 'coach.js?v=23', 'icon.svg', 'manifest.webmanifest'];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(fetch(e.request, /\.(mp3)$/.test(new URL(e.request.url).pathname) ? {} : { cache: 'no-cache' }).then(r => { const copy = r.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {}); return r; }).catch(() => caches.match(e.request, { ignoreSearch: false }).then(r => r || caches.match('index.html'))));
});
