const puppeteer = require('puppeteer-core');
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => { const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new' }); const p = await b.newPage();
await p.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
p.on('pageerror', e => console.log('ERR', e.message));
await p.goto('http://localhost:8765/'); await sleep(800);
await p.evaluate(() => { const s = Object.assign(fresh(), { name: 'Мурзик', kid: 'Василиса', seenVersion: APP_VERSION, rankV: 2, xp: 2600, candies: 300, gems: 30, login: { last: today(), day: 1 }, owned: ['deer', 'loupe', 'bow', 'bowtie', 'crown'], furs: ['galaxy'] }); localStorage.setItem('murlok-detective-v1', JSON.stringify(s)); });
await p.goto('http://localhost:8765/'); await sleep(1200);
await p.evaluate(() => { for (let i = 0; i < 12; i++) Coach.track('mul2', 1); for (let i = 0; i < 6; i++) Coach.track('eq2', 0.3); for (let i = 0; i < 5; i++) Coach.track('g:logic', 1); S.coach.date = ''; save(); });
const snap = async (n, f) => { await p.evaluate(f); await sleep(900); await p.evaluate(() => document.querySelectorAll('.toast').forEach(t => t.remove())); await p.screenshot({ path: `shots/v18-${n}.png`, fullPage: true }); };
await snap('home', () => go('home'));
await snap('academy', () => go('academy'));
await snap('subject', () => go('subject', 'safety'));
await snap('aquiz', () => go('aquiz', 'safety:bullying'));
await snap('fitting', () => { S.fur = 'galaxy'; go('fitting'); });
await p.click('#poses button[data-p="star"]'); await sleep(600); await p.screenshot({ path: 'shots/v18-fitting2.png' });
await snap('photo', () => { Photo.state.pose = 'hi'; go('photo'); });
await snap('salon', () => { SHOP_TAB = 'salon'; go('shop'); });
await snap('parents', () => go('parents'));
await snap('schulte', () => go('schulte', 4));
await b.close(); })();
